USE [DBO_GESTAO_LOGISTICA]
GO

-- 25/04/2023 - Versão 1.0 - Juliana P. Santos DBA MD9i
/*

Ticket: 2269443 - Ticket Projeto de Indicadores
Responsável: Adriano Henrique Dantas - PCP
Banco de Dados: DBO_GESTAO_LOGISTICA
Nome do procedimento : STP_ATUALIZA_TB_HISTORICO_OCUPACAO

*/

CREATE PROCEDURE dbo.STP_ATUALIZA_TB_HISTORICO_OCUPACAO
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY

	INSERT INTO DBO_GESTAO_LOGISTICA..TB_HISTORICO_OCUPACAO
		SELECT GETDATE() AS DAT_GERACAO,
			   GETDATE() AS DAT_ATUALIZACAO,
			   SUM(F.VOL_OCUPADO) AS VOLUME_OCUPADO,
			   SUM(F.VOL_ETQ) AS VOL_ETQ,
			   MAX(F.CAPACIDADE_ARMAZENAGEM_REAL)AS CAPACIDADE_ARMAZENAGEM_REAL,
			   SUM(F.VOL_OCUPADO)/MAX(F.CAPACIDADE_ARMAZENAGEM_REAL) AS TX_OCUPACAO_GERAL,
			   SUM(F.VOL_OCUPADO)/SUM(F.VOL_ETQ) AS TX_UTILIZACAO,
			   SUM(F.ENDERECOS) AS ENDERECOS,
			   F.MODULO AS MODULO,
			   F.LOCAL AS LOCAL,
			   F.NIVEL
		FROM
		  (SELECT J.DATA_REF,
				  SUM(J.VOL_OCUP) AS VOL_OCUPADO,
				  CASE
					  WHEN J.STATUS = 'OCUPADO' THEN SUM(J.VOLUME_REAL)
					  ELSE 0
				  END AS VOL_ETQ,
				  D.CAP_ARM_CD AS CAPACIDADE_ARMAZENAGEM_REAL,
				  CASE
					  WHEN J.STATUS = 'OCUPADO' THEN COUNT(DISTINCT(J.ENDERECO))
					  ELSE 0
				  END AS ENDERECOS,
				  (SUM(J.VOL_OCUP)/SUM(D.CAP_ARM_CD)) AS TX_OCUPACAO_GERAL,
				  J.MODULO,
				  J.LOCAL,
				  J.NIVEL
		   FROM
			 (SELECT W.DATA_REF,
					 E.LOCAL_DE_ARMAZENAGEM AS ENDERECO,
					 E.AREA,
					 W.ITEM,
					 W.QTD,
					 W.VOL AS VOL_OCUP,
					 CASE
						 WHEN W.ITEM <> '' THEN 'OCUPADO'
						 ELSE 'VAZIO'
					 END AS STATUS,
					 E.VOLUME_REAL,
					 CASE
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) = 'PAR-' THEN 'ALMOX'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) IN ('PAR2',
																		  'P2ST') THEN 'ALMOX'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) = 'REF-' THEN 'ALMOX'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = 'CF-' THEN 'ALMOX'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '1-' THEN 'ARMAZEM'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = '2UP' THEN 'ARMAZEM'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = '2C-' THEN 'ARMAZEM'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = '2G-' THEN 'ARMAZEM'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = '2FR' THEN 'ARMAZEM'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '3F' THEN 'EDC'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '3E' THEN 'ARMAZEM'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '2-' THEN 'ARMAZEM'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '3-' THEN 'ARMAZEM'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) = 'DRIV' THEN 'ARMAZEM'
					 END AS MODULO,
					 CASE
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) = 'PAR-' THEN 'PAR'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) IN ('PAR2',
																		  'P2ST') THEN 'PAR2'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) = 'REF-' THEN 'REF'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = 'CF-' THEN 'COFRE'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '1-' THEN 'MODULO_1'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = '2UP' THEN 'PICK_TO_BELT'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = '2C-' THEN 'CROSSDOCKING'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = '2G-' THEN 'GAIOLA'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) = '2FR' THEN 'FRACIONADO'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '3F' THEN 'EDC'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '3E' THEN 'ESTANTE_3E'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '2-' THEN 'MODULO_2'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) = '3-' THEN 'MODULO_3'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) = 'DRIV' THEN 'DRIVE'
					 END AS LOCAL,
					 CASE
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) IN ('PAR-',
																		  'PAR2',
																		  'REF-',
																		  'DRIV')
							  AND RIGHT(E.LOCAL_DE_ARMAZENAGEM, 1) IN ('1',
																	   '2',
																	   '3',
																	   '4',
																	   '5',
																	   '6',
																	   '7',
																	   '8',
																	   '9') THEN 'ALTO'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) IN ('PAR-',
																		  'PAR2',
																		  'REF-')
							  AND RIGHT(E.LOCAL_DE_ARMAZENAGEM, 1) = '0' THEN 'BAIXO'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 4) IN ('DRIV')
							  AND RIGHT(E.LOCAL_DE_ARMAZENAGEM, 1) = '0' THEN 'ALTO'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 3) IN ('CF-',
																		  'P2S')
							  AND RIGHT(E.LOCAL_DE_ARMAZENAGEM, 1) IN ('0',
																	   '1',
																	   '2',
																	   '3',
																	   '4',
																	   '5',
																	   '6',
																	   '7') THEN 'BAIXO'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) IN ('1-',
																		  '2-',
																		  '3-')
							  AND RIGHT(E.LOCAL_DE_ARMAZENAGEM, 1) IN ('1',
																	   '2',
																	   '3',
																	   '4',
																	   '5',
																	   '6',
																	   '7') THEN 'ALTO'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) IN ('1-',
																		  '2-',
																		  '3-')
							  AND RIGHT(E.LOCAL_DE_ARMAZENAGEM, 1) IN ('0') THEN 'BAIXO'
						 WHEN SUBSTRING(E.LOCAL_DE_ARMAZENAGEM, 1, 2) IN ('2U',
																		  '2C',
																		  '2G',
																		  '2F',
																		  '3F',
																		  '3E') THEN 'BAIXO'
					 END AS NIVEL
			  FROM DBO_GESTAO_LOGISTICA.DBO.TB_BASE_VOLUME_ENDERECO E
			  LEFT JOIN
				(SELECT B.ENDERECO,
						B.ITEM,
						B.QTD,
						CONVERT(VARCHAR, B.DAT_GERACAO, 105) AS DATA_REF,
						((B.QTD * (V.VL_ALTURA_CS*V.VL_LARGURA_CS*V.VL_PROFUNDIDADE_CS)/QTD_POR_CX_MAE)/1000000) AS VOL
				 FROM DBO_GESTAO_LOGISTICA.DBO.TB_BASE_WMS B
				 LEFT JOIN DBO_GESTAO_LOGISTICA..VW_VOL_PROD_CD V ON B.ITEM = V.CD_PRODUTO) W ON E.LOCAL_DE_ARMAZENAGEM = ENDERECO) J
		   LEFT JOIN DBO_GESTAO_LOGISTICA..TB_CAPACIDADE_ARMAZENAGEM_CD D ON J.DATA_REF = CONVERT(VARCHAR, D.DATA, 105)
		   WHERE DATA_REF IS NOT NULL
			 AND J.LOCAL NOT IN ('EDC',
								 'FRACIONADO',
								 'ESTANTE_3E',
								 'COFRE')
		   GROUP BY J.DATA_REF,
					D.CAP_ARM_CD,
					J.MODULO,
					J.LOCAL,
					J.NIVEL,
					J.STATUS) F
		GROUP BY F.DATA_REF,
				 F.MODULO,
				 F.LOCAL,
				 F.NIVEL

	END TRY
     BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        SELECT 'NOK TEMP WMS' AS MESSAGE;
    END CATCH;
END